<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NodeEditor.UI</RootNamespace>
    <AssemblyName>NodeEditor.UI</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NodeEditor.Core\NodeEditor.Core.csproj" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
  </ItemGroup>
</Project>
